"""add_pipeline_to_contacts

Revision ID: 674ecf862291
Revises: 476e174e8906
Create Date: 2026-05-04 19:21:01.558633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674ecf862291'
down_revision: Union[str, Sequence[str], None] = '476e174e8906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('pipeline', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'pipeline')
    # ### end Alembic commands ###
