// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;
// Forzamos el uso de la clave nueva si la detectada no tiene el prefijo correcto
const SUPABASE_PUBLISHABLE_KEY = rawKey?.startsWith('eyJ') ? rawKey : "REMOVED";

// Blindaje contra variables ausentes para evitar el "pantallazo blanco" crítico
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn("⚠️ Advertencia: Faltan variables de entorno de Supabase. La aplicación podría no funcionar correctamente.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://REMOVED.supabase.co", 
  SUPABASE_PUBLISHABLE_KEY || "placeholder-key", 
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);